model_dir: models
log_dir: logs-res
checkpoints_dir: checkpoints
results: results-res
name: finetune.model
foundation_model: mace-omat-0-small.model
multiheads_finetuning: False 
train_file: train-mgo-dft.xyz
test_file: test-mgo-dft.xyz
valid_fraction: 0.05 
energy_weight: 1.0 
forces_weight: 100.0 
lr: 0.01 
scaling: rms_forces_scaling 
batch_size: 10
max_num_epochs: 10
ema: True
ema_decay: 0.99 
default_dtype: float64
device: cpu
r_max: 6.0 
energy_key: energy_dft
forces_key: forces
seed: 101
freeze: 5
